/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as SmaartyRouteImport } from './routes/smaarty'
import { Route as PlanteraRouteImport } from './routes/plantera'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KalkylatorRouteImport } from './routes/kalkylator'
import { Route as IntegritetRouteImport } from './routes/integritet'
import { Route as ForetagRouteImport } from './routes/foretag'
import { Route as AvtryckRouteImport } from './routes/avtryck'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjektIndexRouteImport } from './routes/projekt.index'
import { Route as VIdRouteImport } from './routes/v.$id'
import { Route as ProjektPontalRouteImport } from './routes/projekt.pontal'
import { Route as ProjektKhasiHillsRouteImport } from './routes/projekt.khasi-hills'
import { Route as ProjektCopperbeltRouteImport } from './routes/projekt.copperbelt'

const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const SmaartyRoute = SmaartyRouteImport.update({
  id: '/smaarty',
  path: '/smaarty',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanteraRoute = PlanteraRouteImport.update({
  id: '/plantera',
  path: '/plantera',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkylatorRoute = KalkylatorRouteImport.update({
  id: '/kalkylator',
  path: '/kalkylator',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetRoute = IntegritetRouteImport.update({
  id: '/integritet',
  path: '/integritet',
  getParentRoute: () => rootRouteImport,
} as any)
const ForetagRoute = ForetagRouteImport.update({
  id: '/foretag',
  path: '/foretag',
  getParentRoute: () => rootRouteImport,
} as any)
const AvtryckRoute = AvtryckRouteImport.update({
  id: '/avtryck',
  path: '/avtryck',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektIndexRoute = ProjektIndexRouteImport.update({
  id: '/projekt/',
  path: '/projekt/',
  getParentRoute: () => rootRouteImport,
} as any)
const VIdRoute = VIdRouteImport.update({
  id: '/v/$id',
  path: '/v/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektPontalRoute = ProjektPontalRouteImport.update({
  id: '/projekt/pontal',
  path: '/projekt/pontal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektKhasiHillsRoute = ProjektKhasiHillsRouteImport.update({
  id: '/projekt/khasi-hills',
  path: '/projekt/khasi-hills',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektCopperbeltRoute = ProjektCopperbeltRouteImport.update({
  id: '/projekt/copperbelt',
  path: '/projekt/copperbelt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avtryck': typeof AvtryckRoute
  '/foretag': typeof ForetagRoute
  '/integritet': typeof IntegritetRoute
  '/kalkylator': typeof KalkylatorRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/plantera': typeof PlanteraRoute
  '/smaarty': typeof SmaartyRoute
  '/villkor': typeof VillkorRoute
  '/projekt/copperbelt': typeof ProjektCopperbeltRoute
  '/projekt/khasi-hills': typeof ProjektKhasiHillsRoute
  '/projekt/pontal': typeof ProjektPontalRoute
  '/v/$id': typeof VIdRoute
  '/projekt/': typeof ProjektIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avtryck': typeof AvtryckRoute
  '/foretag': typeof ForetagRoute
  '/integritet': typeof IntegritetRoute
  '/kalkylator': typeof KalkylatorRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/plantera': typeof PlanteraRoute
  '/smaarty': typeof SmaartyRoute
  '/villkor': typeof VillkorRoute
  '/projekt/copperbelt': typeof ProjektCopperbeltRoute
  '/projekt/khasi-hills': typeof ProjektKhasiHillsRoute
  '/projekt/pontal': typeof ProjektPontalRoute
  '/v/$id': typeof VIdRoute
  '/projekt': typeof ProjektIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avtryck': typeof AvtryckRoute
  '/foretag': typeof ForetagRoute
  '/integritet': typeof IntegritetRoute
  '/kalkylator': typeof KalkylatorRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/plantera': typeof PlanteraRoute
  '/smaarty': typeof SmaartyRoute
  '/villkor': typeof VillkorRoute
  '/projekt/copperbelt': typeof ProjektCopperbeltRoute
  '/projekt/khasi-hills': typeof ProjektKhasiHillsRoute
  '/projekt/pontal': typeof ProjektPontalRoute
  '/v/$id': typeof VIdRoute
  '/projekt/': typeof ProjektIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avtryck'
    | '/foretag'
    | '/integritet'
    | '/kalkylator'
    | '/kontakt'
    | '/om-oss'
    | '/plantera'
    | '/smaarty'
    | '/villkor'
    | '/projekt/copperbelt'
    | '/projekt/khasi-hills'
    | '/projekt/pontal'
    | '/v/$id'
    | '/projekt/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avtryck'
    | '/foretag'
    | '/integritet'
    | '/kalkylator'
    | '/kontakt'
    | '/om-oss'
    | '/plantera'
    | '/smaarty'
    | '/villkor'
    | '/projekt/copperbelt'
    | '/projekt/khasi-hills'
    | '/projekt/pontal'
    | '/v/$id'
    | '/projekt'
  id:
    | '__root__'
    | '/'
    | '/avtryck'
    | '/foretag'
    | '/integritet'
    | '/kalkylator'
    | '/kontakt'
    | '/om-oss'
    | '/plantera'
    | '/smaarty'
    | '/villkor'
    | '/projekt/copperbelt'
    | '/projekt/khasi-hills'
    | '/projekt/pontal'
    | '/v/$id'
    | '/projekt/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvtryckRoute: typeof AvtryckRoute
  ForetagRoute: typeof ForetagRoute
  IntegritetRoute: typeof IntegritetRoute
  KalkylatorRoute: typeof KalkylatorRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  PlanteraRoute: typeof PlanteraRoute
  SmaartyRoute: typeof SmaartyRoute
  VillkorRoute: typeof VillkorRoute
  ProjektCopperbeltRoute: typeof ProjektCopperbeltRoute
  ProjektKhasiHillsRoute: typeof ProjektKhasiHillsRoute
  ProjektPontalRoute: typeof ProjektPontalRoute
  VIdRoute: typeof VIdRoute
  ProjektIndexRoute: typeof ProjektIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smaarty': {
      id: '/smaarty'
      path: '/smaarty'
      fullPath: '/smaarty'
      preLoaderRoute: typeof SmaartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantera': {
      id: '/plantera'
      path: '/plantera'
      fullPath: '/plantera'
      preLoaderRoute: typeof PlanteraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkylator': {
      id: '/kalkylator'
      path: '/kalkylator'
      fullPath: '/kalkylator'
      preLoaderRoute: typeof KalkylatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritet': {
      id: '/integritet'
      path: '/integritet'
      fullPath: '/integritet'
      preLoaderRoute: typeof IntegritetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foretag': {
      id: '/foretag'
      path: '/foretag'
      fullPath: '/foretag'
      preLoaderRoute: typeof ForetagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avtryck': {
      id: '/avtryck'
      path: '/avtryck'
      fullPath: '/avtryck'
      preLoaderRoute: typeof AvtryckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/': {
      id: '/projekt/'
      path: '/projekt'
      fullPath: '/projekt/'
      preLoaderRoute: typeof ProjektIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$id': {
      id: '/v/$id'
      path: '/v/$id'
      fullPath: '/v/$id'
      preLoaderRoute: typeof VIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/pontal': {
      id: '/projekt/pontal'
      path: '/projekt/pontal'
      fullPath: '/projekt/pontal'
      preLoaderRoute: typeof ProjektPontalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/khasi-hills': {
      id: '/projekt/khasi-hills'
      path: '/projekt/khasi-hills'
      fullPath: '/projekt/khasi-hills'
      preLoaderRoute: typeof ProjektKhasiHillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/copperbelt': {
      id: '/projekt/copperbelt'
      path: '/projekt/copperbelt'
      fullPath: '/projekt/copperbelt'
      preLoaderRoute: typeof ProjektCopperbeltRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvtryckRoute: AvtryckRoute,
  ForetagRoute: ForetagRoute,
  IntegritetRoute: IntegritetRoute,
  KalkylatorRoute: KalkylatorRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  PlanteraRoute: PlanteraRoute,
  SmaartyRoute: SmaartyRoute,
  VillkorRoute: VillkorRoute,
  ProjektCopperbeltRoute: ProjektCopperbeltRoute,
  ProjektKhasiHillsRoute: ProjektKhasiHillsRoute,
  ProjektPontalRoute: ProjektPontalRoute,
  VIdRoute: VIdRoute,
  ProjektIndexRoute: ProjektIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
